# Generated by Django 5.1.6 on 2025-03-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_budget_requester',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='approvalrequestform',
            name='current_level',
            field=models.IntegerField(default=1),
        ),
    ]
