# Generated by Django 5.1.6 on 2025-07-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalrequestform',
            name='approval_type',
        ),
    ]
