# Generated by Django 5.1.6 on 2025-05-24 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chat',
            name='chatroom',
        ),
        migrations.RenameField(
            model_name='approvallog',
            old_name='timestamp',
            new_name='approved_at',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='timestamp',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='timestamp',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='approvalrequestform',
            name='current_level',
        ),
        migrations.RemoveField(
            model_name='approvalrequestform',
            name='initiate_dept',
        ),
        migrations.RemoveField(
            model_name='approvalrequestform',
            name='max_level',
        ),
        migrations.AddField(
            model_name='approvalrequestform',
            name='concerned_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concerned_department', to='mainapp.department'),
        ),
        migrations.AddField(
            model_name='approvalrequestform',
            name='current_form_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='approvalrequestform',
            name='current_status',
            field=models.CharField(default='Pending', max_length=255),
        ),
        migrations.AddField(
            model_name='approvalrequestform',
            name='document_enclosed_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalrequestform',
            name='form_max_level',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='approvalrequestform',
            name='payback_period',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.approvalrequestform'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_budget_requester',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'ADMIN'), ('APPROVER', 'APPROVER'), ('MD', 'MD'), ('EMPLOYEE', 'EMPLOYEE')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.businessunit')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.department')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetAllocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEBIT', 'DEBIT'), ('CREDIT', 'CREDIT')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('budget_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='mainapp.budgetallocation')),
            ],
        ),
        migrations.CreateModel(
            name='FormAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('type', models.CharField(blank=True, choices=[('Asset', 'Asset'), ('Form', 'Form')], max_length=10, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mainapp.approvalrequestform')),
            ],
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
