# Generated by Django 5.1.6 on 2025-03-04 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('level', models.PositiveIntegerField()),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.businessunit')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.designation'),
        ),
    ]
