# Generated by Django 5.1.6 on 2025-07-29 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_approvalrequestform_approval_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequestform',
            name='request_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_category', to='mainapp.category'),
        ),
    ]
