# Generated by Django 5.1.6 on 2025-03-19 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_user_is_budget_requester_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='approvallog',
            old_name='timestamp',
            new_name='approved_at',
        ),
        migrations.RenameField(
            model_name='approvalrequestform',
            old_name='max_level',
            new_name='category_max_level',
        ),
        migrations.RenameField(
            model_name='approvalrequestform',
            old_name='current_level',
            new_name='current_category_level',
        ),
        migrations.AddField(
            model_name='approvalrequestform',
            name='current_form_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='approvalrequestform',
            name='form_max_level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='approver',
            name='approver_request_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category'),
        ),
    ]
