# Generated by Django 5.1.6 on 2025-03-22 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_Category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalrequestform',
            name='initiate_dept',
        ),
        migrations.AddField(
            model_name='approvalrequestform',
            name='concerned_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concerned_department', to='mainapp.department'),
        ),
    ]
