# Generated by Django 5.1.6 on 2025-07-29 18:45

import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_approvalrequestform_request_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequestform',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=mainapp.models.approval_pdf_upload_path),
        ),
        migrations.AlterField(
            model_name='formattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=mainapp.models.attachment_upload_path),
        ),
    ]
