# Generated by Django 5.1.6 on 2025-07-29 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_approvalrequestform_pdf_alter_formattachment_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalrequestform',
            name='pdf',
        ),
    ]
