# Generated by Django 5.1.6 on 2025-03-08 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_user_address_user_business_unit_user_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('policy_agreement', models.BooleanField(default=False)),
                ('initiate_dept', models.CharField(max_length=255)),
                ('current_status', models.CharField(default='Pending', max_length=255)),
                ('benefit_to_organisation', models.TextField()),
                ('approval_category', models.CharField(max_length=255)),
                ('approval_type', models.CharField(max_length=255)),
                ('current_level', models.PositiveIntegerField(default=1)),
                ('max_level', models.PositiveIntegerField(default=1)),
                ('rejected', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('notify_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_to', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('date_rejected', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.designation')),
                ('request_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.approvalrequestform')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('per_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sap_code', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.approvalrequestform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
