# Generated by Django 5.1.6 on 2025-03-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_user_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequestform',
            name='category_max_level',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='approvalrequestform',
            name='form_max_level',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
