# Generated by Django 5.1.6 on 2025-04-12 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_approvalrequestform_category_max_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalrequestform',
            name='category_max_level',
        ),
        migrations.RemoveField(
            model_name='approvalrequestform',
            name='current_category_level',
        ),
        migrations.RemoveField(
            model_name='approvalrequestform',
            name='form_category',
        ),
        migrations.RemoveField(
            model_name='approver',
            name='approver_request_category',
        ),
        migrations.AddField(
            model_name='approvalrequestform',
            name='current_status',
            field=models.CharField(default='Pending', max_length=255),
        ),
        migrations.AddField(
            model_name='approvalrequestform',
            name='document_enclosed_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalrequestform',
            name='payback_period',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='FormAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('type', models.CharField(blank=True, choices=[('Asset', 'Asset'), ('Form', 'Form')], max_length=10, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mainapp.approvalrequestform')),
            ],
        ),
    ]
