# Generated by Django 5.1.6 on 2025-03-10 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_designation_business_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequestform',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='approvalrequestitem',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mainapp.approvalrequestform'),
        ),
    ]
