# Generated by Django 5.1.6 on 2025-05-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_chat_chatroom_chat_form_delete_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'ADMIN'), ('APPROVER', 'APPROVER'), ('MD', 'MD'), ('EMPLOYEE', 'EMPLOYEE')], max_length=20, null=True),
        ),
    ]
